# Sprint 3 - Manipulación de Datos I (Breakout)

En este caso de estudio se busca prácticar los fundamentos de manipulación de datos con **Pandas**. Adicionalmente, se va a introducir los primeros criterios para un adecuado ordenamiento de proyectos de análisis de datos:

* Entendimiento del contexto
* Entendimiento de los datos
* Preparación de los datos
* Análisis de datos

## Entendimiento del contexto

Airbnb es una empresa estadounidense que facilita un mercado en línea para alquileres de alojamientos, principalmente casas de particulares para vacaciones, y también ofrece actividades turísticas. Su plataforma, disponible tanto en su sitio web como en su aplicación móvil, conecta a viajeros con anfitriones que ofrecen sus propiedades. Airbnb no es dueño de las propiedades que se ofrecen; su ganancia proviene de las comisiones que recibe por cada reserva realizada. Fundada en 2008, Airbnb es una abreviatura de su nombre original, *Air Bed and Breakfast*.

## Entendimiento de los datos

El conjunto de datos con el que trabajarás forma parte de la iniciativa *Airbnb Inside* y proporciona información sobre los anuncios de alojamientos en casas particulares en la ciudad de Nueva York. Este conjunto de datos incluye detalles sobre los anuncios, como descripciones completas y puntuaciones de reseñas promedio, reseñas de usuarios con identificación única y comentarios detallados, y calendarios con información de precios y disponibilidad para cada anuncio y día.

### Tarea 1

Comencemos familiarizándonos con la información con la que vamos a trabajar. PAra esto, carga el dataset **airbnb.csv** y recuerda importar previamente las librerías que podrías necesitar.

In [ ]:
import pandas as pd

df_airbnb = pd.read_csv("airbnb.csv")

Imprime la información sobre la estructura general del dataset.

In [9]:
df_airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 22 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   instant_bookable                102494 non-null  object
 10  cancellation_policy             102523 non-null  object
 11  room type                       102599 non-null  object
 12  Construction year               102385 non-null  float64
 13  price                           102352 non-null  float64
 14  service fee                     102326 non-null  float64
 15  minimum nights                  102190 non-null  float64
 16  number of reviews               102416 non-null  float64
 17  last review                     86706 non-null   object
 18  reviews per month               86720 non-null   float64
 19  review rate number              102273 non-null  float64
 20  calculated host listings count  102280 non-null  float64
 21  availability 365                102151 non-null  float64
dtypes: float64(11), int64(2), object(9)
memory usage: 17.2+ MB

Genera una muestra aleatoria de 10 filas del dataset.

In [10]:
df_airbnb.sample(10)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,instant_bookable,...,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
54891,31317635,UWS 2C Large private bedroom 1,87643936315,verified,Chiu Yi,Manhattan,Upper West Side,40.80189,-73.96612,True,...,2003.0,943.0,189.0,3.0,4.0,2/11/2022,2.18,3.0,7.0,299.0
94012,52924164,Charming Brooklyn Gem with Beautiful Views,263193611,verified,Kareem,Brooklyn,Midwood,40.61379,-73.96826,True,...,2007.0,602.0,120.0,3.0,4.0,5/31/2018,0.26,4.0,1.0,18.0
28992,17013618,Cozy private room in the heart of Nolita / Soho,80944073818,verified,Larasati,Manhattan,Nolita,40.72347,-73.99302,True,...,2021.0,1080.0,216.0,2.0,2.0,2/25/2019,0.11,3.0,1.0,0.0
5747,4175404,Beautiful Studio in posh Upper East,22494874701,verified,Cristina,Manhattan,Upper East Side,40.76610,-73.95730,False,...,2015.0,1118.0,224.0,2.0,160.0,6/27/2019,2.76,1.0,1.0,77.0
20121,12114164,Private room on Lovely block in Greenpoint,56713367257,verified,Dawn,Brooklyn,Greenpoint,40.72641,-73.94657,False,...,2021.0,167.0,33.0,20.0,7.0,4/28/2019,0.27,1.0,3.0,342.0
50027,28631248,"The Brooklyn Loft, 30 minutes from Manhattan",79757170860,unconfirmed,Eli,Brooklyn,Crown Heights,40.67210,-73.93042,True,...,2006.0,1090.0,218.0,1.0,151.0,3/1/2022,6.21,4.0,1.0,320.0
12758,8047579,Cute Apartement in Williamsburg,5192121517,unconfirmed,Z,Brooklyn,Williamsburg,40.70935,-73.95207,True,...,2012.0,709.0,142.0,1.0,0.0,NaN,NaN,3.0,1.0,276.0
47,1027294,"1 Stop fr. Manhattan! Private Suite,Landmark B...",81253735818,unconfirmed,Victoria,Queens,Long Island City,40.74771,-73.94740,True,...,2022.0,916.0,183.0,NaN,248.0,7/1/2019,2.25,NaN,1.0,26.0
74146,41952172,Quite and cozy room in Manatthan,31279907237,verified,Camille,Manhattan,East Harlem,40.79795,-73.93448,True,...,2009.0,1006.0,201.0,2.0,20.0,6/14/2019,4.38,5.0,1.0,52.0
7518,5153527,Sunny lofty BR on Express A/D line,45772560250,verified,Esther,Manhattan,Harlem,40.82417,-73.94496,False,...,2020.0,1116.0,223.0,1.0,0.0,NaN,NaN,4.0,1.0,355.0

### Tarea 2

Muestra un resumen estadístico de las variables numéricas.

In [11]:
df_airbnb.describe(exclude = "object")

,id,host id,lat,long,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102352.000000,102326.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,625.293536,125.026924,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,331.671614,66.325739,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,50.000000,10.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,340.000000,68.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,624.000000,125.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,913.000000,183.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,1200.000000,240.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

Muestra ahora un resumen estadístico de las variables tipo texto.

In [12]:
df_airbnb.describe(include = "object")

,NAME,host_identity_verified,host name,neighbourhood group,neighbourhood,instant_bookable,cancellation_policy,room type,last review
count,102349,102310,102193,102570,102583,102494,102523,102599,86706
unique,61281,2,13190,7,224,2,3,4,2477
top,Home away from home,unconfirmed,Michael,Manhattan,Bedford-Stuyvesant,False,moderate,Entire home/apt,6/23/2019
freq,33,51200,881,43792,7937,51474,34343,53701,2443

## Preparación de los datos

### Tarea 1

Ajusta los nombres de las columnas para que se encuentren en formato *snake_case*.

In [13]:
df_airbnb.columns = [col.lower().replace(" ","_") for col in df_airbnb.columns]
df_airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 22 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   name                            102349 non-null  object
 2   host_id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host_name                       102193 non-null  object
 5   neighbourhood_group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   instant_bookable                102494 non-null  object
 10  cancellation_policy             102523 non-null  object
 11  room_type                       102599 non-null  object
 12  construction_year               102385 non-null  float64
 13  price                           102352 non-null  float64
 14  service_fee                     102326 non-null  float64
 15  minimum_nights                  102190 non-null  float64
 16  number_of_reviews               102416 non-null  float64
 17  last_review                     86706 non-null   object
 18  reviews_per_month               86720 non-null   float64
 19  review_rate_number              102273 non-null  float64
 20  calculated_host_listings_count  102280 non-null  float64
 21  availability_365                102151 non-null  float64
dtypes: float64(11), int64(2), object(9)
memory usage: 17.2+ MB

### Tarea 2

Identifica el porcentaje de valores faltantes existentes en cada una de las columnas del dataset, respecto al total de filas.

In [14]:
valores_faltantes = df_airbnb.isnull().sum()
num_filas = df_airbnb.shape[0]
print(100 * valores_faltantes / num_filas)

id                                 0.000000
name                               0.243667
host_id                            0.000000
host_identity_verified             0.281679
host_name                          0.395715
neighbourhood_group                0.028265
neighbourhood                      0.015595
lat                                0.007797
long                               0.007797
instant_bookable                   0.102340
cancellation_policy                0.074075
room_type                          0.000000
construction_year                  0.208579
price                              0.240743
service_fee                        0.266084
minimum_nights                     0.398639
number_of_reviews                  0.178364
last_review                       15.490404
reviews_per_month                 15.476759
review_rate_number                 0.317742
calculated_host_listings_count     0.310919
availability_365                   0.436651
dtype: float64

Da tratamiento a valores perdidos conforme los siguientes criterios:

* Para la columna minimum_nights imputa el valor de la mediana.
* Para la columna neighbourhood_group imputa el valor de la moda.
* Elimina las filas con valores perdidos en las columnas price y construction_year.

In [15]:
#Imputar mediana en minimun_nights
mediana = df_airbnb["minimum_nights"].median()
df_airbnb["minimum_nights"] = df_airbnb["minimum_nights"].fillna(mediana)

In [16]:
#Imputar moda en neighbourhood_group
moda = df_airbnb["neighbourhood_group"].mode()[0]
df_airbnb["neighbourhood_group"] = df_airbnb["neighbourhood_group"].fillna(moda)

In [17]:
#Eliminar filas con valores perdidos en price y construction_year
df_airbnb = df_airbnb.dropna(subset=["price", "construction_year"])

Para el resto de columnas con valores perdidos:

* Si la columna es numérica sustituye los valores faltantes por 0.
* Si la columna es de tipo texto sustituye los valores por la palabra "unknown".

In [18]:
for col in df_airbnb.columns:
    if df_airbnb[col].dtype == "object":
        df_airbnb[col] = df_airbnb[col].fillna("unknown")
    elif df_airbnb[col].dtype in ["int64", "float64"]:
        df_airbnb[col] = df_airbnb[col].fillna(0)

Comprueba si aún quedan valores perdidos en el dataset.

In [19]:
valores_faltantes = df_airbnb.isnull().sum()
num_filas = df_airbnb.shape[0]
print(100 * valores_faltantes / num_filas)

id                                0.0
name                              0.0
host_id                           0.0
host_identity_verified            0.0
host_name                         0.0
neighbourhood_group               0.0
neighbourhood                     0.0
lat                               0.0
long                              0.0
instant_bookable                  0.0
cancellation_policy               0.0
room_type                         0.0
construction_year                 0.0
price                             0.0
service_fee                       0.0
minimum_nights                    0.0
number_of_reviews                 0.0
last_review                       0.0
reviews_per_month                 0.0
review_rate_number                0.0
calculated_host_listings_count    0.0
availability_365                  0.0
dtype: float64

### Tarea 3

Cambia el tipo de variable de la columna construction_year a entero.

In [20]:
df_airbnb["construction_year"] = df_airbnb["construction_year"].astype(int)

### Tarea 4

Verifica si existen filas duplicadas en el dataset.

In [21]:
df_airbnb.duplicated().sum()

541

Elimina las filas duplicadas existentes puesto que las mismas corresponden a errores.

In [22]:
df_airbnb = df_airbnb.drop_duplicates()
df_airbnb.shape

(101601, 22)

## Análisis de datos

### Tarea 1

Muestra cuántas propiedades existen por año de construcción y ordena tu resultado de forma descendente por dicho año.

In [25]:
prop_year = df_airbnb.groupby("construction_year")["id"].count().sort_index(ascending=False)
print(prop_year)

construction_year
2022    5098
2021    4997
2020    5122
2019    5160
2018    5015
2017    5027
2016    4973
2015    5058
2014    5207
2013    4980
2012    5089
2011    5018
2010    5119
2009    5132
2008    5183
2007    5076
2006    5175
2005    5090
2004    4995
2003    5087
Name: id, dtype: int64

Muestra cuántas propiedades existen por grupos de barrios y ordena tu resultado de forma descendente por el conteo.

In [26]:
prop_nb = df_airbnb.groupby("neighbourhood_group")['id'].count().sort_values(ascending=False)
print(prop_nb)

neighbourhood_group
Manhattan        43381
Brooklyn         41442
Queens           13147
Bronx             2684
Staten Island      945
brookln              1
manhatan             1
Name: id, dtype: int64

### Tarea 2

Muestra cuál es la calificación promedio de clientes por tipo de propiedad. Solamente considera aquellos casos con al menos 5 opiniones.

In [27]:
df_filtered = df_airbnb[df_airbnb["number_of_reviews"] >= 5]
rate_type = df_filtered.groupby("room_type")["review_rate_number"].mean()
print(rate_type)

room_type
Entire home/apt    3.250831
Hotel room         3.505495
Private room       3.267787
Shared room        3.246403
Name: review_rate_number, dtype: float64

Repite el ejercicio anterior pero ahora presenta los resultados detallando los mismos por tipo de propiedad y grupo de barrio. Excluye también aquellos grupos de barrios que están "mal escritos".

In [ ]:
grupos = ["Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island"]
df_filtered = df_filtered.query("neighbourhood_group in @grupos")
rate_type_group = df_filtered.pivot_table(
    index = "room_type",
    columns = "neighbourhood_group",
    values = "review_rate_number",
    aggfunc = "mean"
)
print(rate_type_group)

neighbourhood_group     Bronx  Brooklyn  Manhattan    Queens  Staten Island
room_type
Entire home/apt      3.335196  3.224045   3.244074  3.361671       3.277620
Hotel room                NaN  4.000000   3.448718  3.750000            NaN
Private room         3.275696  3.267608   3.255023  3.282154       3.396285
Shared room          3.245283  3.235135   3.206226  3.390805       3.000000