# Sprint 3 - Manipulación de Datos I (Ejercicios)

En los ejercicios a continuación se busca practicar los fundamentos de manipulación de datos con **Pandas**, a fin de fortalecer tus habilidades técnicas en funciones y métodos de esta librería. En concreto revisarás los siguientes temas:

* Carga y entendimiento de datos.
* Tratamiento de valores ausentes.
* Tratamiento de duplicados.
* Filtrado por indexación.
* Filtrado por consulta.
* Agrupamiento de datos.

## Carga y entendimiento de datos

### Ejercicio 1

Importa la librería **Pandas** y carga el dataset [**autos_ws.csv**](https://raw.githubusercontent.com/jsaraujo5081/material_curso_data_science/refs/heads/main/datasets/autos_ws.csv).

In [1]:
# Cargar libreria
import pandas as pd

# Cargar datos
df = pd.read_csv("https://raw.githubusercontent.com/jsaraujo5081/material_curso_data_science/refs/heads/main/datasets/autos_ws.csv")

### Ejercicio 2

Muestra la información de la estructura y las características generales del dataset.

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 177185 entries, 0 to 177184
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   DateCrawled        177185 non-null  float64
 1   Price              177185 non-null  int64
 2   VehicleType        158468 non-null  str
 3   RegistrationYear   177185 non-null  int64
 4   Gearbox            167420 non-null  str
 5   Power              177185 non-null  int64
 6   Model              167320 non-null  str
 7   Kilometer          177185 non-null  int64
 8   RegistrationMonth  177185 non-null  int64
 9   FuelType           160823 non-null  str
 10  Brand              177185 non-null  str
 11  NotRepaired        141594 non-null  str
 12  DateCreated        177185 non-null  int64
 13  NumberOfPictures   177185 non-null  int64
 14  PostalCode         177185 non-null  int64
 15  LastSeen           177185 non-null  float64
dtypes: float64(2), int64(8), str(6)
memory usage: 26.6 MB

Imprime una muestra aleatoria de 10 elementos del dataset.

In [3]:
df.sample(10)

,DateCrawled,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,RegistrationMonth,FuelType,Brand,NotRepaired,DateCreated,NumberOfPictures,PostalCode,LastSeen
102654,42441.74291,12600,convertible,2006,manual,150,eos,70000,10,petrol,volkswagen,no,42441,0,49179,42467.40703
83643,42440.90912,3998,sedan,2002,manual,150,a3,150000,10,petrol,audi,no,42440,0,74177,42458.90802
88613,42450.33027,300,NaN,2016,manual,45,NaN,150000,0,petrol,volkswagen,yes,42450,0,32657,42457.09590
123861,42438.53706,600,small,1996,manual,75,golf,150000,1,petrol,volkswagen,no,42438,0,41464,42449.26295
136592,42463.53016,2999,bus,2003,manual,125,zafira,150000,5,petrol,opel,no,42463,0,85301,42467.62310
115656,42463.87166,8790,sedan,2009,manual,125,a3,100000,1,petrol,audi,no,42463,0,13125,42465.90784
106443,42452.99451,1590,sedan,1994,manual,75,golf,125000,11,petrol,volkswagen,no,42452,0,95445,42466.80263
18958,42437.87288,2500,sedan,1997,manual,110,golf,150000,6,gasoline,volkswagen,NaN,42437,0,73033,42448.19755
102723,42457.74346,4300,sedan,2004,manual,179,a4,150000,6,gasoline,audi,no,42457,0,50189,42466.99023
151559,42457.98565,8700,wagon,2007,manual,170,a4,150000,5,gasoline,audi,no,42457,0,70435,42461.44944

### Ejercicio 3

Verifica los valores únicos existentes en las columnas VehicleType y Gearbox.

In [4]:
# Verificar valores de VehicleType
df["VehicleType"].unique()

<ArrowStringArray>
[nan, 'suv', 'small', 'convertible', 'bus', 'sedan', 'wagon', 'coupe',
 'other']
Length: 9, dtype: str

In [5]:
# Verificar valores de Gearbox
df["Gearbox"].unique()

<ArrowStringArray>
['manual', 'auto', nan]
Length: 3, dtype: str

## Tratamiento de valores ausentes

### Ejercicio 1

Has un conteo de los valores ausentes que existen en cada una de las columnas del dataset.

In [6]:
df.isna().sum()

DateCrawled              0
Price                    0
VehicleType          18717
RegistrationYear         0
Gearbox               9765
Power                    0
Model                 9865
Kilometer                0
RegistrationMonth        0
FuelType             16362
Brand                    0
NotRepaired          35591
DateCreated              0
NumberOfPictures         0
PostalCode               0
LastSeen                 0
dtype: int64

### Ejercicio 2

Imputa en los valores ausentes de la columna VehicleTipe el valor modal.

In [7]:
moda = df["VehicleType"].mode()[0]
df["VehicleType"] = df["VehicleType"].fillna(moda)
df.isna().sum()

DateCrawled              0
Price                    0
VehicleType              0
RegistrationYear         0
Gearbox               9765
Power                    0
Model                 9865
Kilometer                0
RegistrationMonth        0
FuelType             16362
Brand                    0
NotRepaired          35591
DateCreated              0
NumberOfPictures         0
PostalCode               0
LastSeen                 0
dtype: int64

### Ejercicio 3

Imputa en los valores ausentes del resto de columnas la expresión "not defined".

In [8]:
df = df.fillna("not defined")
print(df.isna().sum())

DateCrawled          0
Price                0
VehicleType          0
RegistrationYear     0
Gearbox              0
Power                0
Model                0
Kilometer            0
RegistrationMonth    0
FuelType             0
Brand                0
NotRepaired          0
DateCreated          0
NumberOfPictures     0
PostalCode           0
LastSeen             0
dtype: int64

## Tratamiento de duplicados

### Ejercicio 1

Identifica si existen filas duplicadas en el dataset.

In [9]:
print(df.duplicated().sum())

1

Muestra las filas que estén duplicadas.

In [10]:
df[df.duplicated()]

,DateCrawled,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,RegistrationMonth,FuelType,Brand,NotRepaired,DateCreated,NumberOfPictures,PostalCode,LastSeen
115629,42457.039,1000,small,2002,manual,83,other,150000,1,petrol,suzuki,no,42457,0,66589,42457.36552

### Ejercicio 2

Elimina los valores duplicados existentes. Recuerda resetear los índices luego de esta eliminación.

In [11]:
df = df.drop_duplicates().reset_index(drop = True)
print(df.duplicated().sum())

0

## Filtrado por indexación

### Ejercicio 1

Filtra las primeras 7 filas del dataset usando `iloc`.

In [12]:
df.iloc[:7]

,DateCrawled,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,RegistrationMonth,FuelType,Brand,NotRepaired,DateCreated,NumberOfPictures,PostalCode,LastSeen
0,42453.49464,480,sedan,1993,manual,0,golf,150000,0,petrol,volkswagen,not defined,42453,0,70435,42467.13677
1,42443.53635,9800,suv,2004,auto,163,grand,125000,8,gasoline,jeep,not defined,42443,0,90480,42465.53317
2,42460.72593,3600,small,2008,manual,69,fabia,90000,7,gasoline,skoda,no,42460,0,60437,42466.42872
3,42461.86726,2200,convertible,2004,manual,109,2_reihe,150000,8,petrol,peugeot,no,42461,0,67112,42465.76295
4,42464.98765,14500,bus,2014,manual,125,c_max,30000,8,petrol,ford,not defined,42464,0,94505,42464.98765
5,42455.82938,2000,sedan,2004,manual,105,3_reihe,150000,12,petrol,mazda,no,42455,0,96224,42466.44831
6,42444.95080,999,wagon,1995,manual,115,passat,150000,11,petrol,volkswagen,not defined,42444,0,37269,42461.55296

Filtra las filas 100 a 105 y las columnas 2 a 5 usando `iloc`.

In [13]:
df.iloc[100:106, 2:6]

    VehicleType  RegistrationYear      Gearbox  Power
100       sedan              2016       manual    110
101       sedan              1996         auto      0
102       wagon              2011         auto    313
103       wagon              2009         auto    140
104       small              2001  not defined     41
105       sedan              2007       manual    265

### Ejercicio 2

Filtra las últimas 10 filas de las columnas Price, Brand y Power por indexación de etiquetas usando `loc`.

In [14]:
df.loc[df.shape[0] - 10:, ["Price","Brand","Power"]]

        Price          Brand  Power
177174   1400           opel    125
177175   6500  mercedes_benz    145
177176   5000  mercedes_benz    260
177177    999        renault     95
177178   1490     volkswagen     50
177179   3999            bmw      3
177180   3200           seat    225
177181      0     mitsubishi      0
177182   1199          smart    101
177183   3400     volkswagen    100

## Filtrado por consulta

### Ejercicio 1

Filtra todos los vehículos con un precio superior a 10,100 pero inferior a 10,200 usando el método `query`.

In [15]:
df.query("Price > 10100 and Price < 10200")

,DateCrawled,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,RegistrationMonth,FuelType,Brand,NotRepaired,DateCreated,NumberOfPictures,PostalCode,LastSeen
3456,42434.87199,10199,wagon,2009,auto,177,3er,150000,6,gasoline,bmw,no,42434,0,72587,42465.59569
12723,42449.49666,10150,sedan,2007,manual,163,3er,150000,4,gasoline,bmw,no,42449,0,35789,42460.90653
21476,42461.53535,10199,sedan,2007,manual,122,1er,90000,12,petrol,bmw,no,42461,0,83301,42467.38740
23354,42434.70362,10199,sedan,2017,manual,143,1er,125000,9,gasoline,bmw,not defined,42434,0,65197,42466.98980
31207,42448.94755,10175,sedan,2011,manual,125,astra,80000,3,gasoline,opel,no,42448,0,51427,42450.03302
31274,42444.78260,10199,sedan,2016,manual,333,not defined,150000,0,not defined,bmw,yes,42444,0,54516,42466.82410
44334,42448.78981,10199,sedan,2012,manual,125,leon,70000,7,petrol,seat,no,42448,0,51597,42467.30235
54565,42450.90706,10150,wagon,2010,manual,102,a3,90000,8,petrol,audi,no,42450,0,97855,42467.07306
60333,42449.48491,10199,wagon,2011,manual,122,octavia,100000,5,petrol,skoda,no,42449,0,89347,42449.48491
67920,42458.78517,10199,suv,2008,manual,150,qashqai,125000,3,gasoline,nissan,not defined,42458,0,65203,42459.94001
78710,42462.85883,10199,sedan,2007,manual,143,1er,125000,8,gasoline,bmw,no,42462,0,65197,42466.55418
79982,42454.61602,10150,small,2014,manual,73,clio,30000,3,petrol,renault,no,42454,0,58239,42466.74076
95573,42457.61557,10199,sedan,2010,manual,143,1er,125000,3,gasoline,bmw,no,42457,0,97493,42466.78351
102457,42450.57882,10150,wagon,2009,not defined,114,qashqai,90000,12,petrol,nissan,no,42450,0,52525,42466.40744
110832,42436.49304,10180,wagon,2008,auto,231,3er,150000,4,gasoline,bmw,no,42436,0,84347,42467.48936
111211,42443.78088,10150,sedan,2011,manual,140,astra,50000,3,petrol,opel,no,42443,0,45127,42450.40733
144653,42456.45345,10199,coupe,2005,manual,163,clk,100000,6,petrol,mercedes_benz,no,42456,0,73730,42467.28095
152430,42435.98424,10199,wagon,2006,auto,163,3er,150000,9,gasoline,bmw,no,42435,0,44141,42441.57402
154994,42452.90813,10150,sedan,2006,auto,218,3er,50000,3,petrol,bmw,no,42452,0,14641,42452.90813
155501,42438.45200,10199,sedan,2006,auto,303,3er,150000,6,gasoline,bmw,no,42438,0,33613,42465.61583
156243,42436.73432,10150,wagon,2008,auto,179,a6,150000,10,gasoline,audi,yes,42436,0,86159,42441.49069
158314,42436.03689,10199,sedan,2011,auto,86,golf,60000,4,petrol,volkswagen,no,42435,0,33129,42456.51215
164315,42461.53338,10111,small,2011,manual,101,meriva,20000,5,petrol,opel,no,42461,0,93093,42467.38733
173771,42451.41434,10150,convertible,2005,manual,231,z_reihe,150000,5,petrol,bmw,no,42451,0,38106,42463.84596

### Ejercicio 2

Filtra todos los vehículos de las marcas "volkswagen" o "skoda" y con potencia mayor o igual a 1,600.

In [16]:
df[(df["Brand"].isin(["volkswagen","skoda"])) & (df["Power"] >= 1600)]

,DateCrawled,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,RegistrationMonth,FuelType,Brand,NotRepaired,DateCreated,NumberOfPictures,PostalCode,LastSeen
12616,42457.83170,10900,bus,2009,manual,10520,caddy,150000,6,gasoline,volkswagen,no,42457,0,36272,42467.11600
14471,42450.91536,300,wagon,1996,manual,1999,golf,10000,0,petrol,volkswagen,not defined,42450,0,32825,42452.23963
18103,42461.08063,5400,sedan,2017,manual,2017,transporter,150000,8,gasoline,volkswagen,not defined,42460,0,10178,42465.05444
22260,42439.94260,2500,convertible,1998,manual,7512,golf,150000,6,not defined,volkswagen,not defined,42439,0,68239,42465.63738
22608,42457.48561,1690,sedan,1999,manual,7544,golf,125000,12,petrol,volkswagen,not defined,42457,0,22305,42457.48561
48290,42441.44188,4700,bus,1997,manual,10522,transporter,150000,0,gasoline,volkswagen,not defined,42441,0,87437,42441.44188
48304,42440.73653,1700,sedan,2017,manual,9010,not defined,100000,5,petrol,volkswagen,no,42440,0,99706,42449.09529
56592,42441.41581,350,small,1995,manual,5575,polo,150000,1,petrol,volkswagen,yes,42441,0,29664,42445.34535
64826,42458.62226,300,small,1997,manual,4700,polo,150000,4,petrol,volkswagen,yes,42458,0,13407,42458.65309
69294,42461.67110,2500,bus,2001,manual,2461,transporter,150000,9,gasoline,volkswagen,not defined,42461,0,61250,42467.47023
70859,42448.58179,600,sedan,1997,manual,6006,passat,150000,7,petrol,volkswagen,yes,42448,0,16278,42448.58179
71238,42461.66498,8600,other,2007,not defined,3500,other,150000,12,not defined,volkswagen,not defined,42461,0,30855,42467.57678
78182,42451.70172,0,bus,2006,manual,1700,touran,150000,9,gasoline,volkswagen,no,42451,0,57074,42455.76228
79806,42453.12362,1150,sedan,2016,manual,6011,polo,150000,5,not defined,volkswagen,no,42453,0,49477,42466.82476
92223,42438.95609,3200,sedan,2017,manual,1998,transporter,150000,0,gasoline,volkswagen,not defined,42438,0,45892,42441.84497
120032,42441.37120,6299,small,2012,manual,6062,up,50000,11,petrol,volkswagen,no,42441,0,58511,42441.40770
128851,42461.78355,1250,sedan,2017,manual,9011,golf,60000,5,not defined,volkswagen,no,42461,0,34121,42461.78355
130510,42454.32941,900,wagon,1992,auto,1992,touareg,150000,0,not defined,volkswagen,not defined,42454,0,1665,42466.32406
131333,42435.37001,2800,wagon,1998,manual,11025,passat,150000,6,gasoline,volkswagen,not defined,42435,0,1665,42458.67922
146685,42454.69244,5,bus,2004,manual,2016,not defined,150000,0,not defined,volkswagen,no,42454,0,58515,42457.71984
156790,42462.66332,1250,wagon,2003,auto,1998,passat,5000,12,gasoline,volkswagen,no,42462,0,33719,42466.61538

## Agrupamiento de datos

### Ejercicio 1

Muestra el precio promedio, máximo y mínimo para cada tipo de vehículo usando `groupby`.

In [17]:
# Resolver mediante el metodo describe
(
    df
    .groupby("VehicleType")
    ["Price"].describe()
    [["mean","max","min"]]
)

                    mean      max  min
VehicleType
bus          5510.592781  20000.0  0.0
convertible  6814.260926  20000.0  0.0
coupe        6065.179263  20000.0  0.0
other        3518.177659  19990.0  0.0
sedan        4058.152862  20000.0  0.0
small        2675.824438  20000.0  0.0
suv          9083.577654  20000.0  0.0
wagon        4889.602000  20000.0  0.0

In [18]:
# Resolver mediante el metodo agg
(
    df
    .groupby("VehicleType")
    .agg(
        mean = ("Price", "mean"),
        max = ("Price", "max"),
        min = ("Price", "min")
    )
)

                    mean    max  min
VehicleType
bus          5510.592781  20000    0
convertible  6814.260926  20000    0
coupe        6065.179263  20000    0
other        3518.177659  19990    0
sedan        4058.152862  20000    0
small        2675.824438  20000    0
suv          9083.577654  20000    0
wagon        4889.602000  20000    0

### Ejercicio 2

Muestra en una sola tabla resumen el precio promedio, el kilometraje mediano y la cantidad de modelos por marca.

In [19]:
(
    df
    .groupby("Brand")
    .agg(
        precio_prom = ("Price","mean"),
        km_med = ("Kilometer","median"),
        models_q = ("Model","nunique")
    )
)

                 precio_prom    km_med  models_q
Brand
alfa_romeo       3696.027803  150000.0         7
audi             6279.700041  150000.0        17
bmw              6157.133031  150000.0        11
chevrolet        5542.279097  100000.0         6
chrysler         3694.548697  150000.0         7
citroen          3566.289062  150000.0         8
dacia            5871.701271   80000.0         6
daewoo           1047.101083  150000.0         6
daihatsu         1632.257895  125000.0         8
fiat             2735.537332  150000.0        11
ford             3150.521894  150000.0        15
honda            3667.404486  150000.0         6
hyundai          5219.275346  125000.0         6
jaguar           6706.715953  150000.0         4
jeep             6857.039437  150000.0         5
kia              5087.241352  125000.0         8
lada             3358.468750   60000.0         5
lancia           2277.483193  150000.0         8
land_rover       8598.630189  150000.0        10
mazda            3647.464455  150000.0         9
mercedes_benz    5933.542543  150000.0        19
mini             8963.924574  100000.0         5
mitsubishi       2903.620801  150000.0         8
nissan           3984.510311  150000.0        10
opel             2769.161903  150000.0        17
peugeot          3119.600618  150000.0         7
porsche         11002.005556  150000.0         5
renault          2248.071859  150000.0        11
rover            1292.052000  150000.0         5
saab             3568.629032  150000.0         4
seat             3990.154687  150000.0        11
skoda            5904.627907  150000.0         8
smart            3500.148134  100000.0         5
sonstige_autos   4973.327396  100000.0         1
subaru           3564.133005  150000.0         6
suzuki           3923.566696  125000.0         5
toyota           4776.137435  150000.0         9
trabant          1674.436823   50000.0         3
volkswagen       4380.311756  150000.0        23
volvo            4284.242046  150000.0        10